### ISSUE TITLE
An error occurs in the "rouge 1.9.1"

### ISSUE THREAD

**Issue by usagi-f** [rejahrehim/gulp-hologram#5]
when i used the "rouge 1.9.1", an error occured.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-hologram'
/Library/Ruby/Gems/2.0.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: already initialized constant Rouge::Lexers::Shell::KEYWORDS
/Library/Ruby/Gems/2.0.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: previous definition of KEYWORDS was here
/Library/Ruby/Gems/2.0.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: already initialized constant Rouge::Lexers::Shell::BUILTINS
/Library/Ruby/Gems/2.0.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: previous definition of BUILTINS was here

    at Socket.<anonymous> (/Users/....../....../node_modules/gulp-hologram/index.js:96:30)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by MaikelGG** [comment]
@usagi-f 
I had the same problem:

- gem uninstall rouge
- gem install rouge -v 1.9.0

Then I changed the gemfile.lock to use this version. 
Worked for me.

**Comment by Novak99** [comment]
Worked for me to.
